spring:
  application:
    name: "notify"
  threads:
    virtual:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3316/finance?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "{cipher}f34a736fbc13b15d3061fa1c417170b0a66990a978af7fe98cc16a2a8b5c072f"
    password: "{cipher}f34a736fbc13b15d3061fa1c417170b0a66990a978af7fe98cc16a2a8b5c072f"
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Updated to newer dialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/finance/protocol/openid-connect/certs"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

server:
  port: 8083

info:
  app:
    name: "notification-service"
    description: "Notification Service Application"
    version: "1.0.0"

logging:
  level:
    com:
      finance:
        notificationservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"